#pagebreak()
= Emoji Symbols <sec:emoji>

This is an incomplete list for all emoji goto #link("https://typst.app/docs/reference/symbols/emoji/")[here]

If the emoji module is imported the `#emoji` can be removed

```typst
#import emoji: *
```

#table(
  columns: (6%, 29%, 6%, 29%, 6%, 29%),
  stroke: none,
  align: left+horizon,
  table.header([*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*]),
  table.cell(colspan:6)[#align(center)[*Smileys*]],
  [#emoji.face], ```typst #emoji.face```,
  [#emoji.baby], ```typst #emoji.baby```,
  [#emoji.alien], ```typst #emoji.alien```,
  [#emoji.alien.monster], ```typst #emoji.alien.monster```,
  [#emoji.alien.monster], ```typst #emoji.alien.monster```,
  [#emoji.eye], ```typst #emoji.eye```,
  [#emoji.eyes], ```typst #emoji.eyes```,
  [#emoji.face.grin], ```typst #emoji.face.grin```,
  [#emoji.face.angry], ```typst #emoji.face.angry```,
  [#emoji.face.angry.red], ```typst #emoji.face.angry.red```,
  [#emoji.face.anguish], ```typst #emoji.face.anguish```,
  [#emoji.face.astonish], ```typst #emoji.face.astonish```,
  [#emoji.face.bandage], ```typst #emoji.face.bandage```,
  [#emoji.face.beam], ```typst #emoji.face.beam```,
  [#emoji.face.concern], ```typst #emoji.face.concern```,
  [#emoji.face.cool], ```typst #emoji.face.cool```,
  [#emoji.face.cover], ```typst #emoji.face.cover```,
  [#emoji.face.down], ```typst #emoji.face.down```,
  [#emoji.face.down.sweat], ```typst #emoji.face.down.sweat```,
  [#emoji.face.drool], ```typst #emoji.face.drool```,
  [#emoji.face.explode], ```typst #emoji.face.explode```,
  [#emoji.face.eyeroll], ```typst #emoji.face.eyeroll```,
  [#emoji.face.friendly], ```typst #emoji.face.friendly```,
  [#emoji.face.fear], ```typst #emoji.face.fear```,
  [#emoji.face.fear.sweat], ```typst #emoji.face.fear.sweat```,
  [#emoji.face.fever], ```typst #emoji.face.fever```,
  [#emoji.face.flush], ```typst #emoji.face.flush```,
  [#emoji.face.halo], ```typst #emoji.face.halo```,
  [#emoji.face.happy], ```typst #emoji.face.happy```,
  [#emoji.face.heart], ```typst #emoji.face.heart```,
  [#emoji.face.hearts], ```typst #emoji.face.hearts```,
  [#emoji.face.heat], ```typst #emoji.face.heat```,
  [#emoji.face.kiss], ```typst #emoji.face.kiss```,
  [#emoji.face.kiss.heart], ```typst #emoji.face.kiss.heart```,
  [#emoji.face.kiss.blush], ```typst #emoji.face.kiss.blush```,
  [#emoji.face.joy], ```typst #emoji.face.joy```,
  [#emoji.face.lie], ```typst #emoji.face.lie```,
  [#emoji.face.mask], ```typst #emoji.face.mask```,
  [#emoji.face.meh], ```typst #emoji.face.meh```,
  [#emoji.face.melt], ```typst #emoji.face.melt```,
  [#emoji.face.neutral], ```typst #emoji.face.neutral```,
  [#emoji.face.party], ```typst #emoji.face.party```,
  [#emoji.face.peek], ```typst #emoji.face.peek```,
  [#emoji.face.plead], ```typst #emoji.face.plead```,
  [#emoji.face.relief], ```typst #emoji.face.relief```,
  [#emoji.face.vomit], ```typst #emoji.face.vomit```,
  [#emoji.face.unhappy], ```typst #emoji.face.unhappy```,
  [#emoji.face.wow], ```typst #emoji.face.wow```,
  [#emoji.face.yawn], ```typst #emoji.face.yawn```,
  [#emoji.face.wink], ```typst #emoji.face.wink```,
  [#emoji.face.zip], ```typst #emoji.face.zip```,
  [#emoji.finger.l], ```typst #emoji.finger.l```,
  [#emoji.finger.t], ```typst #emoji.finger.t```,
  [#emoji.finger.b], ```typst #emoji.finger.b```,
  [#emoji.finger.m], ```typst #emoji.finger.m```,
  [#emoji.finger.front], ```typst #emoji.finger.front```,
  [#emoji.fingers.cross], ```typst #emoji.fingers.cross```,
  [#emoji.fingers.pinch], ```typst #emoji.fingers.pinch```,
  [#emoji.fingers.snap], ```typst #emoji.fingers.snap```,
  [#emoji.fist.front], ```typst #emoji.fist.front```,
  [#emoji.fist.r], ```typst #emoji.fist.r```,
  [#emoji.fist.l], ```typst #emoji.fist.l```,
  [#emoji.fist.raised], ```typst #emoji.fist.raised```,
  [#emoji.glasses], ```typst #emoji.glasses```,
  [#emoji.glasses.sun], ```typst #emoji.glasses.sun```,
  [#emoji.hand.raised], ```typst #emoji.hand.raised```,
  [#emoji.hand.r], ```typst #emoji.hand.r```,
  [#emoji.hand.l], ```typst #emoji.hand.l```,
  [#emoji.hand.t], ```typst #emoji.hand.t```,
  [#emoji.hand.b], ```typst #emoji.hand.b```,
  [#emoji.hand.ok], ```typst #emoji.hand.ok```,
  [#emoji.hand.call], ```typst #emoji.hand.call```,
  [#emoji.hand.love], ```typst #emoji.hand.love```,
  [#emoji.hand.part], ```typst #emoji.hand.part```,
  [#emoji.hand.peace], ```typst #emoji.hand.peace```,
  [#emoji.hand.pinch], ```typst #emoji.hand.pinch```,
  [#emoji.hand.rock], ```typst #emoji.hand.rock```,
  [#emoji.hand.wave], ```typst #emoji.hand.wave```,
  [#emoji.hand.write], ```typst #emoji.hand.write```,
  [#emoji.hands.folded], ```typst #emoji.hands.folded```,
  [#emoji.hands.clap], ```typst #emoji.hands.clap```,
  [#emoji.hands.heart], ```typst #emoji.hands.heart```,
  [#emoji.hands.shake], ```typst #emoji.hands.shake```,
  [#emoji.hand.splay], ```typst #emoji.hand.splay```,

  table.cell(colspan:6)[#align(center)[*Drinks*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.beer], ```typst #emoji.beer```,
  [#emoji.beer.clink], ```typst #emoji.beer.clink```,
  [#emoji.cocktail.tropical], ```typst #emoji.cocktail.tropical```,
  [#emoji.coffee], ```typst #emoji.coffee```,
  [#emoji.cup.straw], ```typst #emoji.cup.straw```,
  [#emoji.glass.tumbler], ```typst #emoji.glass.tumbler```,
  [#emoji.glass.clink], ```typst #emoji.glass.clink```,
  [#emoji.glass.milk], ```typst #emoji.glass.milk```,
  [#emoji.teapot], ```typst #emoji.teapot```,
  [#emoji.teacup], ```typst #emoji.teacup```,
  [#emoji.mate], ```typst #emoji.mate```,
  [#emoji.soup], ```typst #emoji.soup```,

  table.cell(colspan:6)[#align(center)[*Animals*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.ant], ```typst #emoji.ant```,
  [#emoji.badger], ```typst #emoji.badger```,
  [#emoji.bat], ```typst #emoji.bat```,
  [#emoji.beetle], ```typst #emoji.beetle```,
  [#emoji.bee], ```typst #emoji.bee```,
  [#emoji.beetle], ```typst #emoji.beetle```,
  [#emoji.beetle.lady], ```typst #emoji.beetle.lady```,
  [#emoji.beaver], ```typst #emoji.beaver```,
  [#emoji.bear], ```typst #emoji.bear```,
  [#emoji.bison], ```typst #emoji.bison```,
  [#emoji.boar], ```typst #emoji.boar```,
  [#emoji.bug], ```typst #emoji.bug```,
  [#emoji.butterfly], ```typst #emoji.butterfly```,
  [#emoji.camel], ```typst #emoji.camel```,
  [#emoji.camel.dromedar], ```typst #emoji.camel.dromedar```,
  [#emoji.cat], ```typst #emoji.cat```,
  [#emoji.chicken], ```typst #emoji.chicken```,
  [#emoji.chicken.male], ```typst #emoji.chicken.male```,
  [#emoji.chipmunk], ```typst #emoji.chipmunk```,
  [#emoji.cockroach], ```typst #emoji.cockroach```,
  [#emoji.cricket], ```typst #emoji.cricket```,
  [#emoji.crocodile], ```typst #emoji.crocodile```,
  [#emoji.dino.pod], ```typst #emoji.dino.pod```,
  [#emoji.dino.rex], ```typst #emoji.dino.rex```,
  [#emoji.dodo], ```typst #emoji.dodo```,
  [#emoji.dog], ```typst #emoji.dog```,
  [#emoji.dolphin], ```typst #emoji.dolphin```,
  [#emoji.duck], ```typst #emoji.duck```,
  [#emoji.egg], ```typst #emoji.egg```,
  [#emoji.elephant], ```typst #emoji.elephant```,
  [#emoji.fairy], ```typst #emoji.fairy```,
  [#emoji.feather], ```typst #emoji.feather```,
  [#emoji.fish], ```typst #emoji.fish```,
  [#emoji.flamingo], ```typst #emoji.flamingo```,
  [#emoji.fly], ```typst #emoji.fly```,
  [#emoji.goat], ```typst #emoji.goat```,
  [#emoji.giraffe], ```typst #emoji.giraffe```,
  [#emoji.hedgehog], ```typst #emoji.hedgehog```,
  [#emoji.hippo], ```typst #emoji.hippo```,

  table.cell(colspan:6)[#align(center)[*Flowers*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.fleur], ```typst #emoji.fleur```,
  [#emoji.flower.hibiscus], ```typst #emoji.flower.hibiscus```,
  [#emoji.flower.lotus], ```typst #emoji.flower.lotus```,
  [#emoji.flower.pink], ```typst #emoji.flower.pink```,
  [#emoji.flower.rose], ```typst #emoji.flower.rose```,
  [#emoji.flower.sun], ```typst #emoji.flower.sun```,
  [#emoji.flower.wilted], ```typst #emoji.flower.wilted```,
  [#emoji.flower.yellow], ```typst #emoji.flower.yellow```,
  [#emoji.plant], ```typst #emoji.plant```,

  table.cell(colspan:6)[#align(center)[*Food*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.avocado], ```typst #emoji.avocado```,
  [#emoji.aubergine], ```typst #emoji.aubergine```,
  [#emoji.banana], ```typst #emoji.banana```,
  [#emoji.broccoli], ```typst #emoji.broccoli```,
  [#emoji.burger], ```typst #emoji.burger```,
  [#emoji.cake.slice], ```typst #emoji.cake.slice```,
  [#emoji.carrot], ```typst #emoji.carrot```,
  [#emoji.chocolate], ```typst #emoji.chocolate```,
  [#emoji.corn], ```typst #emoji.corn```,
  [#emoji.cucumber], ```typst #emoji.cucumber```,
  [#emoji.fries], ```typst #emoji.fries```,
  [#emoji.honey], ```typst #emoji.honey```,

  table.cell(colspan:6)[#align(center)[*Objects*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.bin], ```typst #emoji.bin```,
  [#emoji.bomb], ```typst #emoji.bomb```,
  [#emoji.bone], ```typst #emoji.bone```,
  [#emoji.books], ```typst #emoji.books```,
  [#emoji.book], ```typst #emoji.book```,
  [#emoji.book.open], ```typst #emoji.book.open```,
  [#emoji.bell], ```typst #emoji.bell```,
  [#emoji.bell.not], ```typst #emoji.bell.not```,
  [#emoji.briefcase], ```typst #emoji.briefcase```,
  [#emoji.broom], ```typst #emoji.broom```,
  [#emoji.brush], ```typst #emoji.brush```,
  [#emoji.bubbles], ```typst #emoji.bubbles```,
  [#emoji.cabinet.file], ```typst #emoji.cabinet.file```,
  [#emoji.chair], ```typst #emoji.chair```,
  [#emoji.coffin], ```typst #emoji.coffin```,
  [#emoji.compass], ```typst #emoji.compass```,
  [#emoji.comet], ```typst #emoji.comet```,
  [#emoji.hook], ```typst #emoji.hook```,

  table.cell(colspan:6)[#align(center)[*Sport*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.baseball], ```typst #emoji.baseball```,
  [#emoji.billiards], ```typst #emoji.billiards```,
  [#emoji.boxing], ```typst #emoji.boxing```,
  [#emoji.chess], ```typst #emoji.chess```,
  [#emoji.climbing], ```typst #emoji.climbing```,
  [#emoji.football], ```typst #emoji.football```,

  table.cell(colspan:6)[#align(center)[*Vehicles*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.airplane], ```typst #emoji.airplane```,
  [#emoji.bike], ```typst #emoji.bike```,
  [#emoji.boat], ```typst #emoji.boat```,
  [#emoji.boat.sail], ```typst #emoji.boat.sail```,
  [#emoji.boat.speed], ```typst #emoji.boat.speed```,
  [#emoji.cablecar], ```typst #emoji.cablecar```,
  [#emoji.car], ```typst #emoji.car```,
  [#emoji.car.front], ```typst #emoji.car.front```,
  [#emoji.car.racing], ```typst #emoji.car.racing```,
  [#emoji.ship], ```typst #emoji.ship```,
  [#emoji.motorcycle], ```typst #emoji.motorcycle```,
  [#emoji.wheelchair.motor], ```typst #emoji.wheelchair.motor```,

  table.cell(colspan:6)[#align(center)[*Building*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.castle.eu], ```typst #emoji.castle.eu```,
  [#emoji.castle.jp], ```typst #emoji.castle.jp```,
  [#emoji.circus], ```typst #emoji.circus```,
  [#emoji.factory], ```typst #emoji.factory```,
  [#emoji.hospital], ```typst #emoji.hospital```,
  [#emoji.office], ```typst #emoji.office```,
  [#emoji.house], ```typst #emoji.house```,
  [#emoji.museum], ```typst #emoji.museum```,
  [#emoji.crane], ```typst #emoji.crane```,

  table.cell(colspan:6)[#align(center)[*Weather*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.cloud], ```typst #emoji.cloud```,
  [#emoji.cloud.dust], ```typst #emoji.cloud.dust```,
  [#emoji.cloud.rain], ```typst #emoji.cloud.rain```,
  [#emoji.cloud.snow], ```typst #emoji.cloud.snow```,
  [#emoji.cloud.storm], ```typst #emoji.cloud.storm```,
  [#emoji.cloud.sun], ```typst #emoji.cloud.sun```,
  [#emoji.cloud.sun.hidden], ```typst #emoji.cloud.sun.hidden```,
  [#emoji.cloud.sun.rain], ```typst #emoji.cloud.sun.rain```,
  [#emoji.cloud.thunder], ```typst #emoji.cloud.thunder```,
  [#emoji.drop], ```typst #emoji.drop```,
  [#emoji.drops], ```typst #emoji.drops```,
  [#emoji.sun], ```typst #emoji.sun```,

  table.cell(colspan:6)[#align(center)[*Special*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.checkmark.heavy], ```typst #emoji.checkmark.heavy```,
  [#emoji.checkmark.box], ```typst #emoji.checkmark.box```,
  [#emoji.circle.black], ```typst #emoji.circle.black```,
  [#emoji.circle.white], ```typst #emoji.circle.white```,
  [#emoji.circle.stroked], ```typst #emoji.circle.stroked```,
  [#emoji.copyright], ```typst #emoji.copyright```,
  [#emoji.crossmark], ```typst #emoji.crossmark```,
  [#emoji.crossmark.box], ```typst #emoji.crossmark.box```,
  [#emoji.excl], ```typst #emoji.excl```,
  [#emoji.explosion], ```typst #emoji.explosion```,
  [#emoji.fire], ```typst #emoji.fire```,
  [#emoji.firecracker], ```typst #emoji.firecracker```,
  [#emoji.flag.white], ```typst #emoji.flag.white```,
  [#emoji.flag.black], ```typst #emoji.flag.black```,
  [#emoji.flag.goal], ```typst #emoji.flag.goal```,
  [#emoji.flag.red], ```typst #emoji.flag.red```,
  [#emoji.globe.am], ```typst #emoji.globe.am```,
  [#emoji.globe.as.au], ```typst #emoji.globe.as.au```,
  [#emoji.globe.eu.af], ```typst #emoji.globe.eu.af```,
  [#emoji.globe.meridian], ```typst #emoji.globe.meridian```,
  [#emoji.hash], ```typst #emoji.hash```,
  [#emoji.notes], ```typst #emoji.notes```,
  [#emoji.notes.triple], ```typst #emoji.notes.triple```,
  [#emoji.ast], ```typst #emoji.ast```,

  table.cell(colspan:6)[#align(center)[*Technology*]],
  [*Sym*], [*Raw*], [*Sym*], [*Raw*], [*Sym*], [*Raw*],
  [#emoji.battery], ```typst #emoji.battery```,
  [#emoji.battery.low], ```typst #emoji.battery.low```,
  [#emoji.brightness.high], ```typst #emoji.brightness.high```,
  [#emoji.brightness.low], ```typst #emoji.brightness.low```,
  [#emoji.bubble.speech.l], ```typst #emoji.bubble.speech.l```,
  [#emoji.bubble.speech.r], ```typst #emoji.bubble.speech.r```,
  [#emoji.calendar], ```typst #emoji.calendar```,
  [#emoji.camera], ```typst #emoji.camera```,
  [#emoji.camera.movie], ```typst #emoji.camera.movie```,
  [#emoji.cassette], ```typst #emoji.cassette```,
  [#emoji.clip], ```typst #emoji.clip```,
  [#emoji.clipboard], ```typst #emoji.clipboard```,
  [#emoji.clamp], ```typst #emoji.clamp```,
  [#emoji.clock.one], ```typst #emoji.clock.one```,
  [#emoji.clock.two], ```typst #emoji.clock.two```,
  [#emoji.clock.alarm], ```typst #emoji.clock.alarm```,
  [#emoji.computer], ```typst #emoji.computer```,
  [#emoji.computermouse], ```typst #emoji.computermouse```,
  [#emoji.controller], ```typst #emoji.controller```,
  [#emoji.crab], ```typst #emoji.crab```,
  [#emoji.disc.cd], ```typst #emoji.disc.cd```,
  [#emoji.email], ```typst #emoji.email```,
  [#emoji.floppy], ```typst #emoji.floppy```,
  [#emoji.flashlight], ```typst #emoji.flashlight```,
  [#emoji.folder], ```typst #emoji.folder```,
  [#emoji.folder.open], ```typst #emoji.folder.open```,
  [#emoji.gear], ```typst #emoji.gear```,
  [#emoji.hammer], ```typst #emoji.hammer```,
  [#emoji.hammer.wrench], ```typst #emoji.hammer.wrench```,
  [#emoji.headphone], ```typst #emoji.headphone```,
  [#emoji.laptop], ```typst #emoji.laptop```,
)
