##################################################
# Variables
#
open := if os() == "linux" {
  "xdg-open"
} else if os() == "macos" {
  "open"
} else {
  "start \"\" /max"
}

project_dir   := justfile_directory()
project_name  := file_stem(justfile_directory())

typst_version := "typst -V"
typst_github  := "https://github.com/typst/typst --tag v0.13.1"

option_script := "00-templates/scripts/change-options.bash"
output_dir    := "05-pdf"
doc_name      := "main"
type          := "full"
lang          := "en"

##################################################
# COMMANDS
#
# List all commands
@default:
  just --list

# Information about the environment
@info:
  echo "Environment Informations\n------------------------\n"
  echo "    OS          : {{os()}}({{arch()}})"
  echo "    Open        : {{open}}"
  echo "    Typst       : `{{typst_version}}`"
  echo "    Projectdir  : {{project_dir}}"
  echo "    Projectname : {{project_name}}"

# install required sw
[windows]
[linux]
@install:
  echo "Install typst"
  cargo install --git {{typst_github}}

# install required sw
[macos]
@install:
  echo "Install typst"
  brew install typst

# watch a typ file for continuous incremental build
watch file_name=doc_name:
  typst c {{file_name}}.typ
  just open {{file_name}}
  typst w {{file_name}}.typ

# open pdf
open file_name=doc_name:
  {{open}} {{file_name}}.pdf

# build, rename and copy a typ file to a pdf
@pdf file_name=doc_name type=type lang=lang:
  echo "--------------------------------------------------"
  echo "-- Generate {{file_name}}.pdf with type {{type}} in language {{lang}}"
  echo "--"
  typst c {{file_name}}.typ --input lang={{lang}} --input type={{type}}
  mkdir -p {{output_dir}}
  if [[ "{{type}}" == "full" ]] ;then mv {{file_name}}.pdf "{{output_dir}}/{{project_name}}_{{lang}}.pdf"; fi
  if [[ "{{type}}" == "minimal" ]] ;then mv {{file_name}}.pdf "{{output_dir}}/{{project_name}}_minimal_{{lang}}.pdf"; fi
  just clean

# build, rename and copy a typ file in all variants
@pdf-all file_name=doc_name:
  echo "--------------------------------------------------"
  echo "-- Generate all variants of {{file_name}}.pdf"
  echo "--"
  just pdf {{file_name}} full en
  just pdf {{file_name}} full de
  just pdf {{file_name}} full fr
  just pdf {{file_name}} minimal en
  just pdf {{file_name}} minimal de
  just pdf {{file_name}} minimal fr

# cleanup intermediate files
[linux]
[macos]
@clean:
  echo "--------------------------------------------------"
  echo "-- Clean {{project_name}}"
  echo "--"
  rm 00-templates/*.pdf || true
  rm 01-settings/*.pdf || true
  rm 02-main/**/*.pdf || true
  rm 03-tail/*.pdf || true
  rm 04-resources/*.pdf || true

# cleanup intermediate files
[windows]
@clean:
  echo "--------------------------------------------------"
  echo "-- Clean {{project_name}}"
  echo "--"
  del /q /s 00-templates\*.pdf 2>nul
  del /q /s 01-settings\*.pdf 2>nul
  del /q /s 02-main\**\*.pdf 2>nul
  del /q /s 03-tail\*.pdf 2>nul
  del /q /s 04-resources\*.pdf 2>nul
